org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=false
# Don't set "nonTransitiveRClass" to true; if you do you won't be able to access R.attr.colorAccent,
# R.attr.backgroundColor, R.style.Theme_MaterialComponents_DayNight and R.id.alertTitle.