plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace 'ir.mahdiparastesh.instatools'
    compileSdk 33
    buildToolsVersion '34.0.0 rc4'

    signingConfigs {
        main {
            storeFile file('D:\\Experimental\\mahdiparastesh.jks')
            keyAlias 'instatools'
            storePassword "${System.getenv("JERK")}"
            keyPassword "${System.getenv("JERK")}"
        }
    }

    defaultConfig {
        applicationId 'ir.mahdiparastesh.instatools'
        minSdk 21
        targetSdk 33
        versionCode 68
        versionName '26.3.5'
        signingConfig signingConfigs.main
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    buildFeatures { viewBinding true }

    buildTypes {
        debuggee {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    android.variantFilter { if (it.buildType.name in ['debug', 'androidTest']) it.setIgnore(true) }
}

dependencies {
    def room_version = '2.5.1'
    def media2_version = '1.2.1'

    implementation 'androidx.activity:activity-ktx:1.7.1' // only for ActivityResultLauncher
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation "androidx.media2:media2-widget:$media2_version"
    implementation "androidx.media2:media2-player:$media2_version"
    implementation 'androidx.recyclerview:recyclerview-selection:1.1.0'
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.6.1'
    implementation 'com.airbnb.android:lottie:6.0.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    //noinspection GradleDependency
    implementation 'com.tbuonomo:dotsindicator:4.2'
    implementation 'ir.mahdiparastesh:chipslayoutmanager:0.4.5'
    implementation 'org.apache.commons:commons-imaging:1.0-alpha3'
    implementation 'org.apache.commons:commons-text:1.10.0' // StringEscapeUtils
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1'
}
