plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace 'ir.mahdiparastesh.instatools'
    compileSdk 33
    buildToolsVersion '33.0.0'

    signingConfigs {
        main {
            storeFile file('D:\\Experimental\\mahdiparastesh.jks')
            keyAlias 'instatools'
            storePassword "${System.getenv("JERK")}"
            keyPassword "${System.getenv("JERK")}"
        }
    }

    defaultConfig {
        applicationId 'ir.mahdiparastesh.instatools'
        minSdk 21
        targetSdk 33
        versionCode 63
        versionName '24.2.5'
        signingConfig signingConfigs.main
    }

    buildTypes {
        debuggee {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // applicationIdSuffix = ".beth"
        }
    }
    android.variantFilter { if (it.buildType.name in ['debug', 'androidTest']) it.setIgnore(true) }
    // product flavours caused silly caching of the RESes.

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions { jvmTarget = '1.8' }
    buildFeatures { viewBinding true }
}

//noinspection SpellCheckingInspection
dependencies {
    def room_version = '2.4.3'
    def glide_version = '4.14.2'
    def media2_version = '1.2.1'

    implementation 'androidx.activity:activity-ktx:1.6.1' // only for ActivityResultLauncher
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation "androidx.media2:media2-widget:$media2_version"
    implementation "androidx.media2:media2-player:$media2_version"
    implementation 'androidx.recyclerview:recyclerview-selection:1.1.0'
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.5.0'
    implementation 'com.airbnb.android:lottie:5.2.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    kapt "com.github.bumptech.glide:compiler:$glide_version"
    implementation "com.github.bumptech.glide:glide:$glide_version"
    implementation 'com.github.fulcrum1378:ChipsLayoutManager:5140e08'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'com.google.code.gson:gson:2.10'
    //implementation 'com.googlecode.mp4parser:isoparser:1.1.22'
    //noinspection GradleDependency
    implementation 'com.tbuonomo:dotsindicator:4.2'
    implementation 'org.apache.commons:commons-imaging:1.0-alpha3'
    implementation 'org.apache.commons:commons-text:1.10.0' // StringEscapeUtils
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
}

/*
* com.android.build.gradle.internal.tasks.databinding.DataBindingGenBaseClassesTask uses a newly
* deprecated Gradle class called IncrementalTaskInputs which needs to be replaced by InputChanges
* class, ignore "Deprecated Gradle features were used in this build, making it incompatible with
* Gradle 8.0." warning during build.
*/
