plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

android {
    namespace 'ir.mahdiparastesh.instatools'
    compileSdk 34
    buildToolsVersion = '34.0.0'

    signingConfigs {
        main {
            storeFile file("${System.getenv("JKS_PATH")}")
            storePassword "${System.getenv("JKS_PASS")}"
            keyAlias 'instatools'
            keyPassword "${System.getenv("JKS_PASS")}"
        }
    }

    defaultConfig {
        applicationId 'ir.mahdiparastesh.instatools'
        minSdk 21
        targetSdk 34
        versionCode 72
        versionName '28.4.5'
        signingConfig signingConfigs.main
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_20; targetCompatibility JavaVersion.VERSION_20
    }
    kotlinOptions { jvmTarget = '20' }
    buildFeatures { viewBinding true }

    buildTypes {
        debuggee {
            debuggable true
            minifyEnabled false
            matchingFallbacks = ['debug'] // temporarily for DotsIndicator
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    android.variantFilter { if (it.buildType.name in ['debug', 'androidTest']) it.setIgnore(true) }
}

dependencies {
    def room_version = '2.6.0-beta01'
    def media2_version = '1.2.1'

    implementation 'androidx.activity:activity-ktx:1.7.2' // only for ActivityResultLauncher
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation "androidx.media2:media2-widget:$media2_version"
    implementation "androidx.media2:media2-player:$media2_version"
    implementation 'androidx.recyclerview:recyclerview-selection:1.1.0'
    //noinspection KaptUsageInsteadOfKsp
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-runtime:$room_version"
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'com.airbnb.android:lottie:6.1.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.tbuonomo:dotsindicator:5.0'
    implementation 'ir.mahdiparastesh:chipslayoutmanager:0.5.0'
    implementation 'org.apache.commons:commons-imaging:1.0-alpha3'
    implementation 'org.apache.commons:commons-text:1.10.0' // StringEscapeUtils
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
